---
openio_data_mounts:
  - { partition: '/dev/sdb', mountpoint: "/var/lib/oio/sds" }
openio_metadata_mounts:
  - { partition: '/dev/sdb', mountpoint: "/var/lib/oio/sds" }
#openio_bind_address: "172.17.0.33"
...
