---
- name: Generate beanstalkd inventory
  set_fact:
    inventory: "{{ inventory | combine({ 'namespaces': { namespace: { 'services': new_item } } }, recursive=true) }}"
  vars:
    new_item:
      beanstalkd:
        - id: "{{ namespace }}-beanstalkd-{{ openio_beanstalkd_serviceid }}"
          ip: "{{ openio_beanstalkd_bind_address }}"
          port: "{{ openio_beanstalkd_bind_port  }}"
          partition: ""
          volume: "{{ openio_metadata_mounts[0]['mountpoint'] }}/{{ namespace }}/beanstalkd-{{ openio_beanstalkd_serviceid }}"
          location: ""
          config: {}
  when:
    - openio_metadata_mounts is defined
    - "'backs' in group_names"
...
