---
- name: Generate rawx inventory
  set_fact:
    inventory: >-
      {% set _hash = {'id': openio_rawx_id, 'ip': openio_bind_address, 'port': openio_rawx_bind_port | int, 'volume': openio_rawx_volume, 'partition': mount.partition, 'location': openio_rawx_location, 'config': openio_rawx_config} -%}
      {% set _array = inventory.namespaces[namespace].services.rawx | default([]) | union([_hash]) -%}
      {{ inventory | combine({ 'namespaces': { namespace: { 'services': { 'rawx': _array } } } }, recursive=true) }}
  vars:
    openio_rawx_serviceid: "{{ idx }}"
    openio_rawx_id: "{{ namespace }}-rawx-{{ openio_rawx_serviceid }}"
    openio_rawx_config: {}
    openio_rawx_bind_port: "{{ openio_rawx_global_bind_port + idx }}"
    openio_rawx_volume: "{{ mount.mountpoint }}/{{ namespace }}/rawx-{{ openio_rawx_serviceid }}"
  with_items: "{{ openio_data_mounts }}"
  loop_control:
    loop_var: mount
    index_var: idx
  when:
    - openio_metadata_mounts is defined
    - "'rawx' in group_names"
...
