---
- name: Install and configure OpenIO account
  any_errors_fatal: true
  hosts: account
  become : true
  gather_facts: true
  environment: "{{ openio_environment }}"

  roles:
    - role: gridinit
    - role: account
      openio_account_namespace: "{{ namespace }}"
      openio_account_gridinit_dir: "/etc/gridinit.d/"
      openio_account_gridinit_file_prefix: "{{ namespace }}-"
...
