---
- hosts: keystone
  gather_facts: true
  become: true
  environment: "{{ openio_environment }}"

  roles:
    - role: gridinit
    - role: memcached
      openio_memcached_namespace: "{{ namespace }}"
      openio_memcached_gridinit_dir: "/etc/gridinit.d/"
      openio_memcached_gridinit_file_prefix: "{{ namespace }}-"

    - role: keystone
      openio_keystone_namespace: "{{ namespace }}"
      openio_keystone_gridinit_dir: "/etc/gridinit.d/"
      openio_keystone_gridinit_file_prefix: "{{ namespace }}-"
...
