---
- name: "Install rsyslog from {{ ansible_distribution_release }} repository"
  apt:
    name: rsyslog
    state: latest
    default_release: "{{ ansible_distribution_release }}"
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_rsyslog
  until: install_rsyslog is success
  retries: 5
  delay: 2
  tags: install

- name: "Install needed packages"
  apt:
    name: "{{ pkg }}"
    update_cache: true
  with_items:
    - netcat
    - python-kazoo
    - openio-sds-logrotate
    - openio-sds-rsyslog
    - cron
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_pkg
  until: install_pkg is success
  retries: 5
  delay: 2
  tags: install

- name: Set rsyslog configuration
  copy:
    src: "{{ playbook_dir }}/../files/rsyslog_Debian_openio-sds.conf"
    dest: "/etc/rsyslog.d/30-openio-sds.conf"
    owner: root
    group: root
    mode: 0644
  register: _rsyslog_openio
  tags: configure

- name: Reload rsyslog
  systemd:
    name: rsyslog
    state: restarted
  when: _rsyslog_openio is changed
  tags: configure
...
