---
- name: Check python
  hosts: openio:oiofs
  any_errors_fatal: true
  max_fail_percentage: 0
  gather_facts: false
  strategy: linear
  tags:
    - always

  tasks:
    - name: Install python (Debian)
      raw: "which apt && apt update -y && apt install -y python-minimal || true"
      changed_when: false
      check_mode: false
      become: true

    - name: Install python (RedHat)
      raw: "which yum && yum install -y python || true"
      changed_when: false
      check_mode: false
      become: true

- name: Caching facts and set default values
  import_playbook: playbooks/facts.yml
  tags:
    - always
    - facts
    - fact

- name: Checks
  import_playbook: playbooks/checks.yml
  tags:
    - checks
    - check

- name: Install base
  import_playbook: playbooks/install_basic_needs.yml
  tags: base

- name: SDS
  import_playbook: playbooks/openiosds.yml
  tags: sds

- name: Memcached
  import_playbook: playbooks/memcached.yml
  tags:
    - memcached
    - s3

- name: Swift
  import_playbook: playbooks/oioswift.yml
  tags:
    - swift
    - oioswift
    - s3

- name: Post install
  import_playbook: playbooks/postinstall.yml
  tags:
    - post
    - postinstall

- name: Inventory
  import_playbook: playbooks/inventory.yml
  tags: inventory
...
