---
- src: https://github.com/open-io/ansible-role-openio-repository.git
  version: 9c40fc6bbaeb802068301f3b1e70fa32f4c6e252
  name: repositories

- src: http://github.com/open-io/ansible-role-openio-gridinit.git
  version: 3115f2b33f78185460007417b08800669858e64f
  name: gridinit

- src: https://github.com/open-io/ansible-role-openio-oioproxy.git
  version: b3024bc977024895c72f412c473496b110fb917f
  name: oioproxy

- src: http://github.com/open-io/ansible-role-openio-ecd.git
  version: 3bcc2dbbd1ead2e5b4dbf8f64e9e99a2e56ddf45
  name: ecd

- src: http://github.com/open-io/ansible-role-openio-oiofs
  version: 15b894af25b9ee9cd2ff6176311a21444a201025
  name: oiofs

- src: http://github.com/open-io/ansible-role-openio-namespace
  version: 9ccb37fa87c8e2a43ca8da9c7485b14fb842480a
  name: namespace
...
