---
- name: Setup oiofs environment
  hosts: oiofs
  any_errors_fatal: true
  become: true
  gather_facts: true
  environment: "{{ openio_environment }}"

  pre_tasks:
    - name: namespace
      include_role:
        name: namespace
      vars:
        openio_namespace_name: "{{ play_mount.namespace }}"
        openio_namespace_conscience_url: "{{ openio_sds_conscience_address }}:{{ openio_sds_conscience_port }}"
        openio_namespace_oioproxy_url: "{{ play_mount.oioproxy_host }}:{{ play_mount.oioproxy_port }}"
        openio_namespace_ecd_url: "{{ play_mount.ecd_host }}:{{ play_mount.ecd_port }}"
      with_items: oiofs_mountpoints
      loop_control:
        loop_var: play_mount

  roles:
    - role: repositories
      openio_repository_openstack_release: "{{ openio_repository_openstack_release }}"
      openio_repository_products:
        sds:
          release: "{{ openio_sds_release }}"
        oiofs:
          user: "{{ openio_oiofs_customer_login }}"
          password: "{{ openio_oiofs_customer_password }}"
          release: "{{ openio_sds_release }}"

    - role: gridinit
    - role: ecd
      openio_ecd_bind_address: "{{ openio_sds_ecd_address }}"
      openio_ecd_gridinit_dir: /etc/gridinit.d/
      openio_ecd_gridinit_file_prefix: "{{ openio_sds_namespace }}-"

    - role: oioproxy
      openio_oioproxy_bind_address: "{{ openio_sds_oioproxy_address }}"
      openio_oioproxy_gridinit_dir: /etc/gridinit.d/
      openio_oioproxy_gridinit_file_prefix: "{{ openio_sds_namespace }}-"
      openio_oioproxy_serviceid: "1"

- name: Mount oiofs
  hosts: oiofs
  any_errors_fatal: true
  become: true
  gather_facts: true
  environment: "{{ openio_environment }}"
       
  pre_tasks:
    - name: Create container in OpenIO SDS
      command: "openio container create {{ item.container }} \
                  --oio-account {{ item.account }} \
                  --oio-ns {{ item.namespace }}
                  -c Created -f value"
      with_items: "{{ oiofs_mounts }}"
      register: _openio_container_create
      changed_when: _openio_container_create.stdout == "True"

  roles:
    - role: oiofs
...
